variables:
  PROXY: "-Dhttp.proxyHost=cache-etu.univ-artois.fr -Dhttp.proxyPort=3128 -Dhttps.proxyHost=cache-etu.univ-artois.fr -Dhttps.proxyPort=3128 -Dhttp.nonProxyHosts=localhost"

gradle:
  image: gradle
  stage: build
  script: 
      - "gradle $PROXY test"
      - "gradle -Dsonar.login=$SONARTOKEN sonarqube"
  tags: 
     - docker
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/TEST-*.xml
