variables:
  PROXY: "-Dhttp.proxyHost=cache-etu.univ-artois.fr -Dhttp.proxyPort=3128 -Dhttps.proxyHost=cache-etu.univ-artois.fr -Dhttps.proxyPort=3128 -Dhttp.nonProxyHosts=localhost"
  SONARINFO: "-Dsonar.host.url=http://sonarqube.univ-artois.fr/ -Dsonar.login=$SONARTOKEN"

gradle:
  image: gradle:6.7-jdk11
  stage: build
  script: 
      - "gradle $PROXY test"
  tags: 
     - docker
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/TEST-*.xml
